bili_view/bili_view/urls.py
from logres import views
from interview.views import get_interview_index, Add
from myadmin.service import myadmin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    re_path('^$', views.register),
    re_path(r'^index/', views.index),
    #登录
    re_path('^login/$', views.login),
    #注册
    re_path(r'^register/$', views.register),
    #注销函数
    re_path(r'^logoff/$', views.logoff),
    #设置
    re_path(r'settings/$', views.settings),

    re_path(r'myadmin/index/$', myadmin.site.index),
    re_path('myadmin/', myadmin.site.urls),

    #关于面试URL
    re_path(r'^interview/', include("interview.urls")),


    #处理极验滑动验证码的视图函数
    re_path(r'^pc-geetest/register', views.get_geetest),
    #media相关的路由设置
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT})
]

bili_view/logres/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    """
    username: 账户名
    userpass: 密码
    avator: 头像图片
    create_time: 创建用户时间
    """
    username = models.CharField(max_length = 25, null = True, unique = True)
    password = models.CharField(max_length = 30, null = True)
    phone = models.CharField(max_length=11, null=True, unique=True)
    create_time = models.DateTimeField(auto_now_add = True)
    status = models.IntegerField(choices = ((0, '已删除'), (1, '待激活'), (2, '正常')), default = 2)
    avator = models.FileField(upload_to = "avators_pic/", default = "avators_pic/111.png", verbose_name = '头像')

    def __str__(self):
        return self.username

bili_view/logres/views.py
from django.shortcuts import render, HttpResponse, redirect
import json
from logres import myforms, models
from geetest import GeetestLib

pc_geetest_id = "b46d1900d0a894591916ea94ea91bd2c"
pc_geetest_key = "36fc3fe98530eea08dfc6ce76e3d24c4"

# Create your views here.

# 处理请求滑动验证码的函数
def get_geetest(request):
    user_id = 'test'
    gt = GeetestLib(pc_geetest_id, pc_geetest_key)
    status = gt.pre_process(user_id)
    request.session[gt.GT_STATUS_SESSION_KEY] = status
    request.session["user_id"] = user_id
    response_str = gt.get_response_str()
    return HttpResponse(response_str)

#首页
def index(request):
    if request.method == 'GET':
        return render(request, 'index.html')


# 登录函数
def login(request):
    if request.method == "POST":
        # 初始化登录状态字典
        ret = {'status': False, 'mes': None}
        # 获取极验所需验证信息
        gt = GeetestLib(pc_geetest_id, pc_geetest_key)
        challenge = request.POST.get(gt.FN_CHALLENGE, '')
        validate = request.POST.get(gt.FN_VALIDATE, '')
        seccode = request.POST.get(gt.FN_SECCODE, '')
        status = request.session[gt.GT_STATUS_SESSION_KEY]
        user_id = request.session["user_id"]

        # 判断验证码是否正确
        if status:
            result = gt.success_validate(challenge, validate, seccode, user_id)
        else:
            result = gt.failback_validate(challenge, validate, seccode)
        # 如果验证码正确,获取用户数据
        if result:
            # print(request.POST.get('username'))
            # print(request.POST.get('userpass'))
            userinfo = myforms.Login(request.POST)
            # 通过校验
            if userinfo.is_valid():
                request.session['login_user_name'] = userinfo.cleaned_data['username']
                ret['status'] = True
                ret['mes'] = '/index/'

            else:
                ret['mes'] = userinfo.errors
                # print(ret)

        return HttpResponse(json.dumps(ret))
    elif request.method == 'GET':
        form_obj = myforms.Login()
        return render(request, 'login.html', {'forms_obj': form_obj})

# 注册函数
def register(request):
    if request.method == 'GET':
        if request.userinfo:
            return redirect('/index/')
        # 传入空的表单对象生成HTML标签
        form_obj = myforms.Register()
        return render(request, 'resgister.html', {'forms_obj': form_obj})

    else:
        # 创建一个form对象
        reg_obj = myforms.Register(request.POST)
        # print(reg_obj)
        # 初始化状态信息
        res = {'status': False, 'mes': None}
        # 如果通过form校验
        if reg_obj.is_valid():
            print('通过校验')
            avator_img = request.FILES.get('avator')
            # 在数据库创建信息
            models.UserInfo.objects.create(avator=avator_img, **reg_obj.cleaned_data)

            # 改变状态信息
            res['status'] = True
            res['mes'] = '/login/'
            return HttpResponse(json.dumps(res))
        # 未通过form验证
        else:
            print("未通过验证")
            res['mes'] = reg_obj.errors
            return HttpResponse(json.dumps(res))
# 注销函数
def logoff(request):
    if request.session.get('login_user_name'):
        del request.session['login_user_name']
    return redirect('/index/')

# 设置函数
def settings(request):
    if request.method == 'GET':
        return render(request, 'user_set.html')

    else:
        change_field = request.POST.get('change')
        data = request.POST.get('data')
        res = {'success': False, 'reason': None}
        if data and change_field:
            data= json.loads(data)
            # print(data)
            # if change_field == 'name':
            #     new_username = data.get('new_username')
            #     print(new_username)
            #     print('修改名字')
            # elif change_field == 'password':
            #     old_password = data.get('old_password')
            #     new_password = data.get('new_password')
            #     re_password = data.get('re_password')
            #     print(old_password, new_password, re_password)
            #     print('修改密码')
            # elif change_field == 'email':
            #     new_email = data.get('new_email')
            #     print(new_email)
            #     print('修改邮箱')
            set_data = myforms.Clean_Set(change_field, data)
            #返回FALSE
            if set_data.updata_data():
                res['reason'] = '修改成功'
                res['success'] = True
            else:
                res['reason'] = set_data.errors
        else:
            res['reason'] = '请输入正确数据'

        return HttpResponse(json.dumps(res))

bili_view/logres/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>呵呵</title>

    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/index.css">
    {% block css_link %}
    {% endblock %}
</head>
<body>
    <!--头部分-->
    <div class="head">
        <div class="logo">
            <a href="/index/"><img id="head_logo" src="/static/img/head.png"></a>
        </div>
        <div class="user-func">
                <span class="func_item"><a href="/interview/">关于面试题</a></span>

            {% if request.userinfo %}
                <span class="func_item"><a href="/myadmin/showdata/video">查看视频信息</a></span>
                <span class="func_item"><a href="/settings/">设置</a></span>
                <span class="func_item"><a href="/logoff/">注销</a></span>

            {% else %}
                <span class="func_item"><a href="/register/">注册</a></span>
                <span class="func_item"><a href="/login/">登录</a></span>
            {% endif %}
        </div>
    </div>

    <div class="view_body">
        <div class="logo_res">
            <div class="logo_area">
                <img id="body_logo" src="/static/img/background.png">
            </div>
            {%  block body %}
            {% endblock %}
        </div>
    </div>


    <script src="/static/jquery-3.3.1.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

bili_view/logres/templates/index.html
{% extends "base.html" %}

bili_view/logres/templates/login.html
{% extends "base.html" %}

{% block css_link %}
    <link rel="stylesheet" href="/static/login.css">
{% endblock %}

{% block body %}
<div class="login_area">
    <div class="container">
        <div class="row">
            <div class="col-md-11">
                <form class="form-horizontal login-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ forms_obj.username.id_for_label }}" class="col-sm-3 control-label">{{ forms_obj.username.label }}</label>
                    <div class="col-sm-8">
                        {{ forms_obj.username }}
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ forms_obj.password.id_for_label }}" class="col-sm-3 control-label">{{ forms_obj.password.label }}</label>
                    <div class="col-sm-8">
                        {{ forms_obj.password }}
                        <span class="help-block"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-5">
                        <button type="button" class="btn btn-success" id="login-button" >登录</button>
                    </div>
                </div>
                <div id="popup-captcha"></div>

            </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
    <!-- 引入封装了failback的接口--initGeetest -->
    <script src="http://static.geetest.com/static/tools/gt.js"></script>
    <script>
        //ajax发送登录信息并处理
        var handlerPopup = function (captchaObj){
            captchaObj.onSuccess(function(){
                var validate = captchaObj.getValidate();
                $.ajax({
                url: '/login/',
                type: 'POST',
                datatype: 'JSON',
                data:{
                    username: $('#id_username').val(),
                    password: $('#id_password').val(),
                    geetest_challenge: validate.geetest_challenge,
                    geetest_validate: validate.geetest_validate,
                    geetest_seccode: validate.geetest_seccode,
                    csrfmiddlewaretoken: $("input[name = 'csrfmiddlewaretoken']").val()
                },
                success: function(data){
                    var res = JSON.parse(data);
                    if(res.status ){
                        console.log('登录成功');
                        location.href = res['mes']
                    }
                    else{
                        console.log(res.mes);
                        $.each(res.mes, function(k, v){
                            $('#id_'+ k).next('span').text(v[0]).parent().parent().addClass('has-error')
                        })
                    }
                }
            })
            });
            //按键绑定函数
            $('#login-button').click(function(){
               captchaObj.show();
            });
            //将验证码加到该标签内
            captchaObj.appendTo('#popup-captcha')

        };

        //当输入框获得鼠标焦点时，清除之前错误
        $('#id_username, #id_password').focus(function(){
            $(this).next('span').text("").parent().parent().removeClass('has-error');
        });

        // 验证开始需要向网站主后台获取id，challenge，success（是否启用failback）
        $.ajax({
        url: "/pc-geetest/register?t=" + (new Date()).getTime(), // 加随机数防止缓存
        type: "get",
        dataType: "json",
        success: function (data) {
            // 使用initGeetest接口
            // 参数1：配置参数
            // 参数2：回调，回调的第一个参数验证码对象，之后可以使用它做appendTo之类的事件
            initGeetest({
                gt: data.gt,
                challenge: data.challenge,
                product: "popup", // 产品形式，包括：float，embed，popup。注意只对PC版验证码有效
                offline: !data.success // 表示用户后台检测极验服务器是否宕机，一般不需要关注
                // 更多配置参数请参见：http://www.geetest.com/install/sections/idx-client-sdk.html#config
            }, handlerPopup);
        }
    });
    </script>
{% endblock %}
</body>
</html>

bili_view/logres/templates/resgister.html
{% extends "base.html" %}

{% block css_link %}
    <link rel="stylesheet" href="/static/resgister.css">
{% endblock %}

{% block body %}
<div class="res_area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form action="/register/" method="post" class="form-horizontal reg-form"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ forms_obj.username.id_for_label }}"
                               class="col-sm-3 control-label">{{ forms_obj.username.label }}</label>
                        <div class="col-sm-8">
                            {{ forms_obj.username }}
                            <span class="help-block"></span>
                        </div>

                    </div>
                    <div class="form-group">
                        <label for="{{ forms_obj.password.id_for_label }}"
                               class="col-sm-3 control-label">{{ forms_obj.password.label }}</label>
                        <div class="col-sm-8">
                            {{ forms_obj.password }}
                            <span class="help-block"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ forms_obj.phone.id_for_label }}"
                               class="col-sm-3 control-label">{{ forms_obj.phone.label }}</label>
                        <div class="col-sm-8">
                            {{ forms_obj.phone }}
                            <span class="help-block"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-sm-3 control-label">头像</label>
                        <div class="col-sm-9">
                            <label for="id_avator"><img id="avator-img" src="/static/img/default.png"></label>
                            <input type="file" id="id_avator" name="avator" accept="image/*"
                                   style="display: none">
                            <span class="help-block"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-5">
                            <input type="button" class="btn btn-success" id="reg-submit" value="注册">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
    <script>
    //选择头像，并加载预览图
    $('#id_avator').change(function(){

        //创建文件对象
        var filereader = new FileReader();
        //读取选中的文件
        filereader.readAsDataURL(this.files[0]);
        //等待图片加载完成,执行函数
        filereader.onload = function(){
            //找到要改变的标签下的图片
            $('#avator-img').attr("src", filereader.result);
        }


    });

    //用AJax提交数据
    $('#reg-submit').click(function(){
        //创建一个空的FormData对象，并将数据添加进去
        var senddata = new FormData();
        senddata.append('username', $('#id_username').val());
        senddata.append('password', $('#id_password').val());
        senddata.append('phone', $('#id_phone').val());
        senddata.append('csrfmiddlewaretoken', $("[name = 'csrfmiddlewaretoken']").val());
        senddata.append('avator', $('#id_avator')[0].files[0]);
        $.ajax({
            url: '/register/',
            type: 'POST',
            data: senddata,
            datatype: JSON,
            //发送文件对象的必要设置，
            processData: false,
            contentType: false,
            success: function(data){
                //console.log(data);
                var data = JSON.parse(data)
                if (data.status){
                    location.href = data.mes;
                }
                else{
                    //依次对错误信息执行函数
                    $.each(data.mes, function(k, v){
                        //找到对应标签的错误信息标签,并将上级DIV标签加上Class：has error
                        $('#id_' + k).next('span').text(v[0]).parent().parent().addClass('has-error');
                    })
                }
            }
        })
    });
    //找到form下面的input标签，鼠标点击去掉has-error和错误信息

    $("form input").focus(function() {
        $(this).next("span").text("").parent().parent().removeClass('has-error');
    });
</script>
{% endblock %}
</body>
</html>

bili_view/logres/templates/user_set.html
{% extends "base.html" %}

{% block css_link %}
    <link rel="stylesheet" href="/static/user_setting.css">
{% endblock %}


{% block body %}
    <form id="set_area_list">
        {% csrf_token %}
        <div class="set_area">
            <div class="change_info">
                <div class="change_name"><a onclick="display_name()">修改</a></div>
                用户名
            </div>
            <div class="old_info" id="old_name">
                <div class="old_name">{{ request.userinfo.username }}</div>
                <span>你的用户名</span>
            </div>
            <div class="edit_info hide" id="change_name">
                <label id="label_user" for="new_username">新的用户名:</label>
                <input type="text" class="new_info" id="new_username">
                <div class="old_name" style="font-weight: 700">{{ request.userinfo.username }}</div>
                <div class="put_button">
                    <input type="button" value="保存" onclick="send_name()">
                    <input type="button" value="取消" onclick="display_name()">
                </div>
            </div>

        </div>
        <div class="set_area">
            <div class="change_info">
                <div class="change_name"><a onclick="display_password()">修改</a></div>
                密码
            </div>
            <div class="old_info" id="old_password">
                <div class="old_name">********</div>
                <span>你的密码</span>
            </div>
            <div class="edit_info hide" id="change_password">
                <div style="margin-bottom: 3px;">
                    <label id="label_user" for="input_old_password">旧密码:</label>
                    <input type="text" class="new_info" id="input_old_password">
                </div>
                <div style="margin-bottom: 3px;">
                    <label id="label_user" for="input_new_password">新密码:</label>
                    <input type="text" class="new_info" id="input_new_password">
                </div>
                <div style="margin-bottom: 3px;" >
                <label id="label_user" for="input_re_password">确认密码:</label>
                <input type="text" class="new_info" id="input_re_password">
                </div>
                <div class="old_name" style="font-weight: 700">********</div>
                <div class="put_button">
                    <input type="button" value="保存" onclick="send_password()">
                    <input type="button" value="取消" onclick="display_password()">
                </div>
            </div>

        </div>
        <div class="set_area">
            <div class="change_info">
                <div class="change_name"><a onclick="display_phone()">修改</a></div>
                电话
            </div>
            <div class="old_info" id="old_phone">
                <div class="old_name">{{ request.userinfo.phone }}</div>
                <span>电话</span>
            </div>
            <div class="edit_info hide" id="change_phone">
                <label id="label_user" for="new_phone">新电话:</label>
                <input type="text" class="new_info" id="new_phone">
                <div class="old_name" style="font-weight: 700">{{ request.userinfo.email }}</div>
                <div class="put_button">
                    <input type="button" value="保存" onclick="send_phone()">
                    <input type="button" value="取消" onclick="display_phone()">
                </div>
            </div>

        </div>

    </form>
{% endblock %}


{% block script %}
    <script>
        var csrf_val = $("input[name='csrfmiddlewaretoken']").val();
        var send_data = {};
        var input_data = {}
        send_data['csrfmiddlewaretoken'] = csrf_val;
        //显示输入框函数
        function display_name() {
            $("#change_name").toggleClass("hide");
            $("#old_name").toggleClass("hide");
        }
        function display_password() {
            $("#change_password").toggleClass("hide");
            $("#old_password").toggleClass("hide");
        }
        function display_phone() {
            $("#change_phone").toggleClass("hide");
            $("#old_phone").toggleClass("hide");
        }
        //发送数据
        function send_name() {
            var new_username = $('input#new_username').val();
            console.log(new_username);
            input_data['new_username'] = new_username;
            send_data['change'] = 'name';
            gogogo();
        }
        function send_password() {
            var old_password = $('input#input_old_password').val();
            var new_password = $('input#input_new_password').val();
            var re_password = $('input#input_re_password').val();
            console.log(old_password, new_password, re_password);
            input_data['old_password'] = old_password;
            input_data['new_password'] = new_password;
            input_data['re_password'] = re_password;
            send_data['change'] = 'password';
            gogogo();
        }
        function send_phone() {
            var new_phone = $('input#new_phone').val();
            console.log(new_phone);
            input_data['new_phone'] = new_phone;
            send_data['change'] = 'phone';
            gogogo();
        }
        function gogogo() {
            input_data['user_id'] = {{ request.userinfo.pk }}
            send_data['data'] = JSON.stringify(input_data);
            console.log(send_data);
            $.ajax({
                url: '/settings/',
                type: 'POST',
                data: send_data,
                success: function(data) {
                    var data = JSON.parse(data);
                    console.log(data);
                    if (data.success) {
                        location.href = '/index/';
                    }
                    else {
                        $.each(data.reason, function(k, v) {
                            alert(v[0]);
                        });
                    }
                }
            })
        }
    </script>
{% endblock %}